interface Traits {
  Background: string[];
  Body: string[];
  Eyes: string[];
  Hat: string[];
  Mouth: string[];
  Shirt: string[];
}

export const traits: Traits = {
  Background: [
    'Black',
    'Blue',
    'Green',
    'Lime',
    'Purple',
    'Red',
    'Sky Blue',
    'Stars',
    'Tan'
  ],
  Body: [
    'Dark Green',
    'Froggy Green',
    'Glass',
    'Pink',
    'Stone Gray',
    'Toad'
  ],
  Eyes: [
    'Alien',
    'Closed',
    'Cute',
    'Dots',
    'Happy',
    'Mad',
    'Sad',
    'Sleepy',
    'Squint',
    'XX'
  ],
  Hat: [
    'Alien Antenna',
    'Apple',
    'Astronaut Helmet',
    'Bald',
    'Bee Fren',
    'Black Beanie',
    'Black Forg Hat',
    'Blue Beanie',
    'Blue Flower',
    'Blue Mushroom',
    'Chef',
    'Clown',
    'Crown',
    'Devil Horns',
    'Fly Fren',
    'Hair',
    'Halo',
    'Heart',
    'Lady Bug Fren',
    'Lemon',
    'Pink Flower',
    'Propeller',
    'Red Beanie',
    'Red Flower',
    'Red Mushroom',
    'Snail Fren',
    'Sprout',
    'Tadpole Fren',
    'Tella Antenna',
    'Witch',
    'Wizard'
  ],
  Mouth: [
    'Alien',
    'Cheeks',
    'Clown',
    'Derp',
    'Fangs',
    'Frown',
    'Mustache',
    'Plain',
    'Smile',
    'Sus',
    'Tongue'
  ],
  Shirt: [
    'Black Bandana',
    'Black Bow Tie',
    'Black Cloak',
    'Black Dress Shirt',
    'Black Hoodie',
    'Black Stripes',
    'Black Tie Dress Shirt',
    'Black Tie Suit',
    'Blue Bandana',
    'Blue Bow Tie',
    'Blue Dress Shirt',
    'Blue Pajamas',
    'Blue Stripes',
    'Blue Tie Dress Shirt',
    'Blue Tie Suit',
    'Brown Hoodie',
    'Caveman',
    'Chef Apron',
    'Clown',
    'Cow Suit',
    'Kerm',
    'King Cloak',
    'Naked',
    'Orange Astronaut',
    'Pink Hoodie',
    'Pink Pajamas',
    'Red Bandana',
    'Red Bow Tie',
    'Red Stripes',
    'Red Tie Dress Shirt',
    'Red Tie Suit',
    'Robe',
    'White Astronaut',
    'White Dress Shirt',
    'Wizard Cloak'
  ]
}